### ISSUE TITLE
Sidebar is not automatically opening when I edit a MDN page

### ISSUE THREAD

**Issue by MatonAnthony** [mdn/doc-linter-webextension#1]
**Current behavior:** The sidebar is not opening itself when I edit a MDN page.

**Expected behavior:** 
   - On Firefox / Opera : The sidebar should open itself when editing a MDN page.
   - On Chrome / Edge / Safari : Sidebar API is currently unimplemented in those browsers and isn't planned on any of there roadmaps.

**Blockers:**
It isn't currently possible to open a sidebar programmatically (see: https://bugzilla.mozilla.org/show_bug.cgi?id=1341126)

**References:**
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction

**Comment by wbamberg** [comment]
One alternative to using a sidebar would be to inject an iframe into the page using a content script, and host the add-on's interface there.

In general this isn't a very good idea, because uncooperative/hostile pages could subvert the add-on (by drawing stuff over the iframe, for example) but in this case that's not an issue because we can expect pages from developer.mozilla.org to be cooperative :).

**Comment by MatonAnthony** [comment]
Another solution would be to add it to the developer panels when the browser doesn't support SidebarAction API.

**Comment by wbamberg** [comment]
Yes. See also https://github.com/Elchi3/mdn-doc-tests/issues/230 for some more discussion of that :).

**Comment by MatonAnthony** [comment]
Following a conversation with mixedpuppy from the addons team.
It will not be possible to open the sidebar without user interaction due to a design choice.

It will be possible to open the sidebar programmatically but always with an user interaction.

Making this bug unfixable.

**Comment by SebastianZ** [comment]
> It will not be possible to open the sidebar without user interaction due to a design choice.

Yes, very sadly I was not able to convince people that this should work without user interaction.

> It will be possible to open the sidebar programmatically but always with an user interaction.

That would be a good compromise. Though please note [bug 1343817](https://bugzilla.mozilla.org/show_bug.cgi?id=1343817), where opening it programmatically was rejected, and new bugs for APIs requiring user interaction didn't get filed yet, as far as I can see (or they are just not referred to from that bug).

Sebastian

**Comment by MatonAnthony** [comment]
This bug https://bugzilla.mozilla.org/show_bug.cgi?id=1341126 is about opening the sidebar with user interaction.
