### ISSUE TITLE
Add count link to avoid duplicates URL

### ISSUE THREAD

**Issue by MatonAnthony** [mdn/doc-linter-webextension#15]
**Current behavior:** 
There is no test regarding potential link duplicates.

**Expected behavior:**  
There should be a test to provide informations regarding duplicates links for SEO purposes.

**Plan to action:**
_This is only a suggested plan to action_
1. Add a test getting the number of links for a same URL in an article.
2. Define thresholds to return INFO, ERRORS or WARNINGS depending of the amount of link.
3. Implement the feature.

**Actions pending:**
- [X] Wait for the new Rule to be implemented in mdn/doc-linter-rules
- [x] Implement the use of the new package of rules

**Comment by a2sheppy** [comment]
Ideally we would get the following information:

* A warning if there are more than 100 links total within the body (including those generated by macros, preferably)
* An error if there are more than 250 links total within the body
* Warnings if there are more than some given number of links to the same page (I'm not sure right now what that number is)

**Comment by MatonAnthony** [comment]
The linting rule has been added in the rules package by https://github.com/mdn/doc-linter-rules/commit/8a197ac1e28eaf0890ad1e56150402dbeb16a125

I will close this once we release the WebExtension with the new package.

**Comment by MatonAnthony** [comment]
The release is now in AMO pipeline, so I can close this one.
