### ISSUE TITLE
Run test suite also in source view 

### ISSUE THREAD

**Issue by Elchi3** [mdn/doc-linter-webextension#22]
Original issue: https://github.com/Elchi3/mdn-doc-tests/issues/84.

 > Currently the test suite is just run while editing an article within the formatted view. Though the results should also be displayed while you're within the source view.
> 
> To allow the tests to work the same once issue #80 got implemented, the source needs to be turned into HTML.
> 
> Sebastian

**Comment by MatonAnthony** [comment]
Following a conversation with someone from AMO Team.

The feature cannot land in the current state even considering the following facts.

- The code is either provided by the user or coming sanitized from MDN.
- The code is already executed by CKEditor to do his preview.

The proposed solution seem very unsatisfying : 
- Create all the node manually while sanitizing
